name: CICD Build - Javelin Ramparts Server

on:
  push:
    branches:
      - "main"
      - "devops-trigger"
    paths-ignore:
      - "**/*CHANGELOG.md"
      - "*CHANGELOG.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEVOPS_REPO: "javelin-cloud"
  DEVOPS_BRANCH: "devops-trigger"
  CICD_TRIGGER: "enable"
  EVENT_TYPE: "cicd-trigger"

jobs:
  reusable-vars:
    permissions:
      contents: 'read'
    runs-on: ubuntu-24.04
    steps:
      - name: reusable variables
        run: echo "Exposing env vars"
    outputs:
      CICD_TRIGGER: ${{ env.CICD_TRIGGER }}

  javelin-trigger:
    needs:
      - reusable-vars
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-24.04
    if: (needs.reusable-vars.outputs.CICD_TRIGGER == 'enable')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install GitHub CLI
        shell: bash
        run: |-
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        shell: bash
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
  
      - name: Trigger private repo workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository_owner }}/${{ env.DEVOPS_REPO }}/dispatches \
            -f event_type=${{ env.EVENT_TYPE }} \
            -F client_payload[ref]=${{ env.DEVOPS_BRANCH }}

