name: Cron Build - Javelin Ramparts Server

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 1'  # Every Friday at 2:30 AM UTC = 8:00 AM IST

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEVOPS_REPO: "javelin-cloud"
  DEVOPS_BRANCH: "main"
  CICD_TRIGGER: "enable"
  EVENT_TYPE: "cron-trigger"

jobs:
  reusable-vars:
    permissions:
      contents: 'read'
    runs-on: ubuntu-24.04
    steps:
      - name: reusable variables
        run: echo "Exposing env vars"
    outputs:
      CICD_TRIGGER: ${{ env.CICD_TRIGGER }}

  javelin-trigger:
    needs:
      - reusable-vars
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-24.04
    if: (needs.reusable-vars.outputs.CICD_TRIGGER == 'enable')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install GitHub CLI
        run: sudo apt install gh -y

      - name: Trigger private repo workflow
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
        run: |
          echo "Dispatching to repo: $DEVOPS_REPO with event_type: $EVENT_TYPE and ref: $DEVOPS_BRANCH"
  
           gh api --method POST \
            -H "Accept: application/vnd.github+json" \
             https://api.github.com/repos/getjavelin/$DEVOPS_REPO/dispatches \
            -f event_type=$EVENT_TYPE \
            -F client_payload[ref]=$DEVOPS_BRANCH \
